apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubedemo-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: kubedemo
  template:
    metadata:
      labels:
        app: kubedemo
    spec:
      containers:
      - name: kubedemo
        image: vyshnavi1201/newssearch:latest

        ports:

        - containerPort: 5000
